/**
 * Every limit the trading side obeys, in one place.
 *
 * These are code, not prompt. A strategy -- including the model-driven one --
 * can propose whatever it likes; nothing here is negotiable at runtime, and
 * changing a limit means changing this file and shipping it.
 *
 * Values are deliberate starting points for the paper account, sized so a
 * broken strategy is cheap. Tune them once there is enough recorded history to
 * argue from.
 */
export const TRADING_CONFIG = {
  /**
   * Which Korea Investment environment orders may reach. Only ever flip this
   * as a deliberate, reviewed change -- it is the difference between a
   * simulated fill and a real one. The live credentials are also absent from
   * the deployment, so this is the second lock rather than the only one.
   */
  environment: "demo" as "demo" | "real",

  /** Asia/Seoul wall-clock bounds of the trading window. */
  window: {
    openHour: 9,
    openMinute: 10,
    /** No new position may be opened at or after this. */
    lastEntryHour: 10,
    lastEntryMinute: 15,
    /** Everything still held is flattened at this time. */
    closeHour: 10,
    closeMinute: 30,
  },

  limits: {
    /**
     * Entries permitted per day.
     *
     * The brief said five trades; this is a ceiling rather than a quota on
     * purpose. Forcing the fifth entry when nothing is worth buying is how a
     * strategy loses money to satisfy a counter. The strategy is told the
     * budget and allowed to spend less.
     */
    maxEntriesPerDay: 5,
    /** Distinct tickers that may be held at once. */
    maxConcurrentPositions: 3,
    /** Notional cap for a single order, in KRW. */
    maxOrderValueKrw: 1_000_000,
    /** Hard ceiling on orders of any kind, so a loop cannot run away. */
    maxOrdersPerDay: 30,
    /** Candidates the strategy may consider. */
    maxCandidates: 8,
    /**
     * Session halts when the day's loss reaches this fraction of deployed
     * capital. Expressed positive.
     */
    dailyLossLimitPct: 3,
  },

  /**
   * How positions are closed. The strategy has no say in any of this -- exits
   * are generated by the risk gate, never proposed.
   */
  exits: {
    /** Sell the whole position at or below this. */
    stopLossPct: -2,
    /**
     * Scale out above the target rather than selling it all at once: half off
     * at +3%, the rest at +5%. `sellFraction` is of the position size at the
     * moment the rung is reached.
     */
    ladder: [
      { atPct: 3, sellFraction: 0.5 },
      { atPct: 5, sellFraction: 1 },
    ],
    /**
     * Protects what the first rung proved. Once part of the position has been
     * taken off at a profit, a remainder that stalls short of the next rung
     * and gives back to this level is closed out rather than ridden back down
     * to the stop -- the trade already worked, and the point here is to keep
     * that rather than to be right about the rest.
     *
     * Only applies after a rung has been taken; an untouched position is
     * governed by the stop alone.
     */
    giveBackPct: 2,
  },

  /** Candidate screening. */
  screening: {
    /**
     * Traded value against market capitalisation, in percent -- the "is this
     * actually moving relative to its size" test. A large cap ticking over on
     * ordinary volume fails it; a mid cap being repriced passes.
     */
    minTurnoverToMarketCapPct: 1,
    /** Ignore anything below this traded value, in KRW, as too thin to exit. */
    minTurnoverKrw: 5_000_000_000,
    /**
     * Price floor, in KRW. Below this a 2% stop sits inside the tick spread,
     * so the exit rules stop meaning what they say.
     */
    minPriceKrw: 2000,
    /**
     * How far down the turnover ranking to look before screening.
     *
     * Each name costs one throttled quote call at ~1.2s, so this is bounded by
     * the function's 60s budget as much as by usefulness: 15 names is roughly
     * 18 seconds of screening.
     */
    rankPoolSize: 15,
  },

  /**
   * How old the overnight report may be before its sector view is dropped.
   *
   * The gap is legitimately several days: a Korean Monday trades on Friday's
   * US session, and a Korean holiday stretches that further. Four days covers
   * the normal cases without letting last week's read pass as this morning's.
   *
   * Past it the outlook is withheld rather than the day being skipped. The
   * market opens whether or not we have a view, and the agent's default is
   * already to do nothing without a reason -- so less information makes it
   * more cautious, which is the right direction to fail in.
   */
  maxReportAgeDays: 4,

  /** How often the window is evaluated, in minutes. */
  tickIntervalMinutes: 5,
} as const;

export type TradingConfig = typeof TRADING_CONFIG;
