/**
 * Every limit the trading side obeys, in one place.
 *
 * These are code, not prompt. A strategy -- including the model-driven one --
 * can propose whatever it likes; nothing here is negotiable at runtime, and
 * changing a limit means changing this file and shipping it.
 *
 * Values are deliberate starting points for the paper account, sized so a
 * broken strategy is cheap. Tune them once there is enough recorded history to
 * argue from.
 */
export const TRADING_CONFIG = {
  /**
   * Which Korea Investment environment orders may reach. Only ever flip this
   * as a deliberate, reviewed change -- it is the difference between a
   * simulated fill and a real one. The live credentials are also absent from
   * the deployment, so this is the second lock rather than the only one.
   */
  environment: "demo" as "demo" | "real",

  /**
   * What the desk may deploy in a day, in KRW.
   *
   * Deliberately a constant rather than a reading of the account. The paper
   * account holds ₩100m and the live account is expected to hold more than
   * this too; the desk is sized by decision, not by whatever happens to be on
   * deposit. Every position is flattened before the close, so the same amount
   * is available again the next morning regardless of the day's result.
   *
   * Divided evenly among the strategies on duty -- see `strategyBudgetKrw`.
   */
  capitalKrw: 20_000_000,

  /**
   * Asia/Seoul wall-clock bounds of the trading window.
   *
   * Widened from the original 09:10-10:30 morning to make room for a strategy
   * that cannot act until the first 30-minute bar has closed at 09:30 and then
   * needs time for a 2R target to be reached.
   *
   * The flatten is deliberately not 15:30. KRX runs a closing single-price
   * auction from 15:20, so an order sent at the bell does not trade and the
   * position carries overnight -- which would break the premise that the same
   * capital is available again the next morning. 15:15 is still continuous
   * trading, where a market order fills.
   */
  window: {
    openHour: 9,
    openMinute: 10,
    /** No new position may be opened at or after this. */
    lastEntryHour: 11,
    lastEntryMinute: 30,
    /** Everything still held is flattened at this time. */
    closeHour: 15,
    closeMinute: 15,
  },

  limits: {
    /**
     * Entries permitted per strategy per day.
     *
     * A ceiling rather than a quota on purpose. Forcing the last entry when
     * nothing is worth buying is how a strategy loses money to satisfy a
     * counter -- the strategy is told the budget and allowed to spend less.
     *
     * This also fixes the per-order ceiling: a strategy's budget divided by
     * this number. Two entries of half the budget each.
     */
    maxEntriesPerDay: 2,

    /**
     * Hard ceiling on strategy-proposed orders, so a loop cannot run away.
     * Mandatory exits are exempt -- they are generated from the positions
     * actually held, cannot multiply, and blocking one would trap a position
     * the risk rules have already decided to close.
     */
    maxOrdersPerDay: 30,

    /** Candidates a strategy may consider. */
    maxCandidates: 30,

    /**
     * A strategy stops opening positions when its own loss reaches this
     * fraction of the budget allocated to it. Expressed positive.
     */
    strategyLossLimitPct: 5,

    /**
     * Account-wide circuit breaker, against `capitalKrw` rather than against
     * what happens to be deployed. Expressed positive.
     *
     * Both limits gate entries only. Exits are never blocked by a loss limit:
     * the point of hitting one is to stop taking risk, and refusing the sells
     * would do the opposite by trapping the desk in what it already holds.
     */
    dailyLossLimitPct: 10,
  },

  /**
   * How positions are closed. The strategy has no say in any of this -- exits
   * are generated by the risk gate, never proposed.
   */
  exits: {
    /** Sell the whole position at or below this. */
    stopLossPct: -2,
    /**
     * Scale out above the target rather than selling it all at once: half off
     * at +3%, the rest at +5%. `sellFraction` is of the position size at the
     * moment the rung is reached.
     */
    ladder: [
      { atPct: 3, sellFraction: 0.5 },
      { atPct: 5, sellFraction: 1 },
    ],
    /**
     * Protects what the first rung proved. Once part of the position has been
     * taken off at a profit, a remainder that stalls short of the next rung
     * and gives back to this level is closed out rather than ridden back down
     * to the stop -- the trade already worked, and the point here is to keep
     * that rather than to be right about the rest.
     *
     * Only applies after a rung has been taken; an untouched position is
     * governed by the stop alone.
     */
    giveBackPct: 2,
  },

  /** Candidate screening. */
  screening: {
    /**
     * Which KIS ranking lists to merge.
     *
     * Measured, not assumed: the ranking endpoint returns exactly 30 rows with
     * no paging cursor and no `tr_cont` header, and asking for "all markets"
     * (0000) returns what is effectively the KOSPI list, because KOSPI large
     * caps take the top of any turnover ranking. Asking each market separately
     * costs one extra 1.2s call and roughly doubles the pool -- and the names
     * it adds are exactly the ones this screen exists to find, since traded
     * value against market cap favours smaller companies.
     *
     * 0001 is KOSPI, 1001 is KOSDAQ.
     */
    markets: ["0001", "1001"] as const,
    /**
     * Price ranges asked for separately, so the pool is not thirty large caps.
     *
     * The endpoint returns thirty rows whatever is asked of it, ranked by
     * absolute traded value -- which contradicts the screen it feeds. This
     * screen looks for turnover relative to size, and a ₩400억 company trading
     * ₩80억 of itself is exactly what it wants; ₩80억 does not come close to
     * the top thirty. Measured on 2026-09-05, the lowest name in the KOSPI list
     * had traded ₩826억, sixteen times the liquidity floor below.
     *
     * Asking within price bands returns thirty from each, and the low band is
     * where the small caps live. It took the pool from 60 names to 180.
     *
     * Price is a poor stand-in for size and this is not a fix, only a wider
     * window. The endpoint offers no market-cap filter.
     */
    priceBands: [
      [2_000, 10_000],
      [10_000, 50_000],
      [50_000, null],
    ] as const,
    /**
     * Traded value against market capitalisation, in percent -- the "is this
     * actually moving relative to its size" test. A large cap ticking over on
     * ordinary volume fails it; a mid cap being repriced passes.
     */
    minTurnoverToMarketCapPct: 1,
    /** Ignore anything below this traded value, in KRW, as too thin to exit. */
    minTurnoverKrw: 5_000_000_000,
    /**
     * Price floor, in KRW. Below this a 2% stop sits inside the tick spread,
     * so the exit rules stop meaning what they say.
     */
    minPriceKrw: 2000,
    /**
     * How far down each market's ranking to look.
     *
     * 30 is the endpoint's own limit, not a choice -- it returns 30 rows and
     * offers no way to ask for more. The pool is widened by market, not by
     * depth.
     */
    rankPoolSize: 30,
  },

  /**
   * Watching a position between ticks.
   *
   * The five-minute tick is how the desk decides what to buy; it is far too
   * coarse for deciding when to sell. On 2026-09-03 a position read -1.55% at
   * 09:16 and -5.21% at 09:20 -- it crossed the -2% stop somewhere in those
   * four minutes and nothing was watching. The stop is a promise, and a promise
   * checked every five minutes is not one.
   *
   * So while anything is held, a worker polls the balance on this interval and
   * acts on the exits itself. One balance call returns every position's price,
   * which is why the interval can be this short without straining the 1.2s gap
   * the paper environment enforces.
   */
  watch: {
    /** Seconds between polls. */
    intervalSeconds: 15,
    /**
     * How long one invocation runs before handing to the next.
     *
     * Under the 300s function ceiling with room for a poll to finish and the
     * hand-off to be queued.
     */
    invocationSeconds: 240,
    /**
     * Hard ceiling on the chain, and the last thing standing between a bug and
     * a function that re-queues itself forever. Checked before anything else.
     *
     * A full session is 09:10 to 15:15, which is 21,900 seconds, or about 92
     * generations at four minutes each. It was 100 -- and on 2026-09-04 a
     * session held a position for six hours and reached generation 99. The
     * margin was one.
     *
     * 200 is roughly twice a session, which is margin for generations that end
     * early rather than a licence to run longer: the chain is stopped by the
     * closing bell and by the desk going flat long before this matters. Why
     * that session needed 99 instead of 92 is answered by `watch_generations`,
     * which now records what each one did.
     */
    maxGenerations: 200,
    /** A watcher quieter than this is presumed dead and may be replaced. */
    staleHeartbeatSeconds: 90,
    /**
     * A ticker sold within this window is left alone.
     *
     * Deliberately short -- about one poll. It exists for one narrow thing: the
     * seconds between submitting a sale and Korea Investment reducing the
     * orderable quantity it reports back. Outside that window `sellableQuantity`
     * is authoritative and a duplicate cannot oversell anyway.
     *
     * It was 60s and that was worse than having none. Suppression leaves no
     * record and blocks the ticker for the whole window, so a profit ladder
     * that cleared its second rung inside a minute would silently miss it. A
     * duplicate that gets through, by contrast, is refused by the broker, is
     * recorded with a reason, and is retried by the next poll fifteen seconds
     * later. Visible and self-correcting beats invisible and blocked.
     */
    exitCooldownSeconds: 20,
  },

  /**
   * The opening-range strategy's own numbers.
   *
   * Taken from the source specification rather than invented, so that what the
   * strategy does can be checked against the document it came from. The
   * document is a reconstruction of a YouTube method and is explicit that its
   * results are unverified -- these are starting points to be measured, not
   * settled values.
   */
  orb: {
    /** Minutes after the open that form the reference range. */
    rangeMinutes: 30,
    /** Bar size the strategy makes decisions on, in minutes. */
    triggerMinutes: 5,
    /** A breakout bar this many times ATR(14) counts as momentum on its own. */
    giantBarAtrMultiple: 1.5,
    /** ...and this many times the volume average alongside it. */
    giantBarVolumeMultiple: 2.0,
    /** Consecutive bullish bars that count as momentum instead. */
    consecutiveBars: 3,
    atrPeriod: 14,
    volumeMaPeriod: 20,
    /** How near the range high a pullback must come, as a fraction. */
    retestBandBelow: 0.002,
    retestBandAbove: 0.002,
    /** A pin bar's lower wick, as a fraction of the whole bar. */
    pinbarWickFraction: 0.6,
    /** Reward as a multiple of the risk taken. The document's 2R. */
    rewardMultiple: 2.0,
    /** Ticks below the reference low the stop is placed. */
    stopBufferTicks: 1,
    /**
     * How much of its budget the strategy risks on one trade, in percent.
     *
     * This is the other half of the document's sizing rule -- quantity is the
     * risk budget divided by the distance to the stop, so a tight stop buys
     * more shares and a wide one buys fewer, and the loss when the stop is hit
     * is the same either way. The desk's per-order ceiling still applies and
     * the smaller of the two wins.
     */
    riskPerTradePct: 0.5,
    /** Stop-outs before the strategy stands itself down for the day. */
    killSwitchLosses: 2,
    /** Names carried into the session. Each costs one 1.2s call per tick. */
    watchlistSize: 10,
  },

  /**
   * How old the overnight report may be before its sector view is dropped.
   *
   * The gap is legitimately several days: a Korean Monday trades on Friday's
   * US session, and a Korean holiday stretches that further. Four days covers
   * the normal cases without letting last week's read pass as this morning's.
   *
   * Past it the outlook is withheld rather than the day being skipped. The
   * market opens whether or not we have a view, and the agent's default is
   * already to do nothing without a reason -- so less information makes it
   * more cautious, which is the right direction to fail in.
   */
  maxReportAgeDays: 4,

  /** How often the window is evaluated, in minutes. */
  tickIntervalMinutes: 5,
} as const;

export type TradingConfig = typeof TRADING_CONFIG;

/**
 * A single strategy's share of the day's capital.
 *
 * Fixed once at the open and carried in the run's metadata rather than
 * recomputed per tick: adding or retiring a strategy mid-session would
 * otherwise change the budget that orders already placed were sized against.
 */
export function strategyBudgetKrw(liveStrategyCount: number, registeredCount = 1): number {
  // With nothing live -- a shadow session -- the divisor falls back to how many
  // strategies are registered, so each one is sized as it would be if promoted.
  // Sizing a shadow strategy against the whole desk would make its recorded
  // quantities meaningless for judging it later, which is the only reason to
  // run it at all.
  const divisor = liveStrategyCount > 0 ? liveStrategyCount : registeredCount;
  return Math.floor(TRADING_CONFIG.capitalKrw / Math.max(1, divisor));
}

/**
 * The most one order may be worth, for a strategy holding `budgetKrw`.
 *
 * Derived rather than configured, so the entry count and the order ceiling
 * cannot drift apart. Two entries of half the budget, by construction.
 */
export function maxOrderValueKrw(budgetKrw: number): number {
  return Math.floor(budgetKrw / TRADING_CONFIG.limits.maxEntriesPerDay);
}
