/**
 * Every limit the trading side obeys, in one place.
 *
 * These are code, not prompt. A strategy -- including the model-driven one --
 * can propose whatever it likes; nothing here is negotiable at runtime, and
 * changing a limit means changing this file and shipping it.
 *
 * Values are deliberate starting points for the paper account, sized so a
 * broken strategy is cheap. Tune them once there is enough recorded history to
 * argue from.
 */
export const TRADING_CONFIG = {
  /**
   * Which Korea Investment environment orders may reach. Only ever flip this
   * as a deliberate, reviewed change -- it is the difference between a
   * simulated fill and a real one. The live credentials are also absent from
   * the deployment, so this is the second lock rather than the only one.
   */
  environment: "demo" as "demo" | "real",

  /**
   * What the desk may deploy in a day, in KRW.
   *
   * Deliberately a constant rather than a reading of the account. The paper
   * account holds ₩100m and the live account is expected to hold more than
   * this too; the desk is sized by decision, not by whatever happens to be on
   * deposit. Every position is flattened before the close, so the same amount
   * is available again the next morning regardless of the day's result.
   *
   * Divided evenly among the strategies on duty -- see `strategyBudgetKrw`.
   */
  capitalKrw: 20_000_000,

  /** Asia/Seoul wall-clock bounds of the trading window. */
  window: {
    openHour: 9,
    openMinute: 10,
    /** No new position may be opened at or after this. */
    lastEntryHour: 10,
    lastEntryMinute: 15,
    /** Everything still held is flattened at this time. */
    closeHour: 10,
    closeMinute: 30,
  },

  limits: {
    /**
     * Entries permitted per strategy per day.
     *
     * A ceiling rather than a quota on purpose. Forcing the last entry when
     * nothing is worth buying is how a strategy loses money to satisfy a
     * counter -- the strategy is told the budget and allowed to spend less.
     *
     * This also fixes the per-order ceiling: a strategy's budget divided by
     * this number. Two entries of half the budget each.
     */
    maxEntriesPerDay: 2,

    /**
     * Hard ceiling on strategy-proposed orders, so a loop cannot run away.
     * Mandatory exits are exempt -- they are generated from the positions
     * actually held, cannot multiply, and blocking one would trap a position
     * the risk rules have already decided to close.
     */
    maxOrdersPerDay: 30,

    /** Candidates a strategy may consider. */
    maxCandidates: 30,

    /**
     * A strategy stops opening positions when its own loss reaches this
     * fraction of the budget allocated to it. Expressed positive.
     */
    strategyLossLimitPct: 5,

    /**
     * Account-wide circuit breaker, against `capitalKrw` rather than against
     * what happens to be deployed. Expressed positive.
     *
     * Both limits gate entries only. Exits are never blocked by a loss limit:
     * the point of hitting one is to stop taking risk, and refusing the sells
     * would do the opposite by trapping the desk in what it already holds.
     */
    dailyLossLimitPct: 10,
  },

  /**
   * How positions are closed. The strategy has no say in any of this -- exits
   * are generated by the risk gate, never proposed.
   */
  exits: {
    /** Sell the whole position at or below this. */
    stopLossPct: -2,
    /**
     * Scale out above the target rather than selling it all at once: half off
     * at +3%, the rest at +5%. `sellFraction` is of the position size at the
     * moment the rung is reached.
     */
    ladder: [
      { atPct: 3, sellFraction: 0.5 },
      { atPct: 5, sellFraction: 1 },
    ],
    /**
     * Protects what the first rung proved. Once part of the position has been
     * taken off at a profit, a remainder that stalls short of the next rung
     * and gives back to this level is closed out rather than ridden back down
     * to the stop -- the trade already worked, and the point here is to keep
     * that rather than to be right about the rest.
     *
     * Only applies after a rung has been taken; an untouched position is
     * governed by the stop alone.
     */
    giveBackPct: 2,
  },

  /** Candidate screening. */
  screening: {
    /**
     * Which KIS ranking lists to merge.
     *
     * Measured, not assumed: the ranking endpoint returns exactly 30 rows with
     * no paging cursor and no `tr_cont` header, and asking for "all markets"
     * (0000) returns what is effectively the KOSPI list, because KOSPI large
     * caps take the top of any turnover ranking. Asking each market separately
     * costs one extra 1.2s call and roughly doubles the pool -- and the names
     * it adds are exactly the ones this screen exists to find, since traded
     * value against market cap favours smaller companies.
     *
     * 0001 is KOSPI, 1001 is KOSDAQ.
     */
    markets: ["0001", "1001"] as const,
    /**
     * Traded value against market capitalisation, in percent -- the "is this
     * actually moving relative to its size" test. A large cap ticking over on
     * ordinary volume fails it; a mid cap being repriced passes.
     */
    minTurnoverToMarketCapPct: 1,
    /** Ignore anything below this traded value, in KRW, as too thin to exit. */
    minTurnoverKrw: 5_000_000_000,
    /**
     * Price floor, in KRW. Below this a 2% stop sits inside the tick spread,
     * so the exit rules stop meaning what they say.
     */
    minPriceKrw: 2000,
    /**
     * How far down each market's ranking to look.
     *
     * 30 is the endpoint's own limit, not a choice -- it returns 30 rows and
     * offers no way to ask for more. The pool is widened by market, not by
     * depth.
     */
    rankPoolSize: 30,
  },

  /**
   * How old the overnight report may be before its sector view is dropped.
   *
   * The gap is legitimately several days: a Korean Monday trades on Friday's
   * US session, and a Korean holiday stretches that further. Four days covers
   * the normal cases without letting last week's read pass as this morning's.
   *
   * Past it the outlook is withheld rather than the day being skipped. The
   * market opens whether or not we have a view, and the agent's default is
   * already to do nothing without a reason -- so less information makes it
   * more cautious, which is the right direction to fail in.
   */
  maxReportAgeDays: 4,

  /** How often the window is evaluated, in minutes. */
  tickIntervalMinutes: 5,
} as const;

export type TradingConfig = typeof TRADING_CONFIG;

/**
 * A single strategy's share of the day's capital.
 *
 * Fixed once at the open and carried in the run's metadata rather than
 * recomputed per tick: adding or retiring a strategy mid-session would
 * otherwise change the budget that orders already placed were sized against.
 */
export function strategyBudgetKrw(liveStrategyCount: number): number {
  return Math.floor(TRADING_CONFIG.capitalKrw / Math.max(1, liveStrategyCount));
}

/**
 * The most one order may be worth, for a strategy holding `budgetKrw`.
 *
 * Derived rather than configured, so the entry count and the order ceiling
 * cannot drift apart. Two entries of half the budget, by construction.
 */
export function maxOrderValueKrw(budgetKrw: number): number {
  return Math.floor(budgetKrw / TRADING_CONFIG.limits.maxEntriesPerDay);
}
